### ISSUE TITLE
Flowers do not drop

### ISSUE THREAD

**Issue by ringprod** [tumGER/FlowerPower#6] opened 2023-06-21 20:33 UTC
When mining flowers in survival, the item does not drop.

**Comment by AnnsAnns** [comment] 2023-06-22 08:52
Are you talking about the flowers themselves or the petals? The petals are crafted through this crafting recipe as seen in the ReadMe: 
![grafik](https://github.com/tumGER/FlowerPower/assets/25822956/cea92ac7-7409-4272-83db-ced85160ea55)

**Comment by ringprod** [comment] 2023-06-23 00:57
The petals, when they are placed and you mine them, they just disappear and do not drop anything.

**Comment by AnnsAnns** [comment] 2023-06-23 10:31
Oh yeah you're right, thank you for letting me know, it seems like this was a regression caused by internal changes that happened in one Minecraft Snapshot. I'll fix it in the next version.

**Comment by AnnsAnns** [comment] 2023-06-23 11:03
Fixed in v1.1.0

**Closed as completed by AnnsAnns** 2023-06-23 11:03 UTC
Labels: bug

**Comment by AnnsAnns** [comment] 2023-06-23 11:13
https://modrinth.com/mod/flower-power/version/1.1.0
